### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by lztby** [swimlane/pyews#15]
I want use the code to exchang2016, does it support?
if it support,I write this code:
```
from pyews import UserConfiguration, GetInboxRules

userconfig = UserConfiguration(
      'email',
      'password',
)
inboxRules = GetInboxRules('email', userconfig).response
```
then,these are the error:
```
Traceback (most recent call last):
  File "PycharmProjects/inboxRules/test2.py", line 7, in <module>
    inboxRules = GetInboxRules('email', userconfig).response
  File "/opt/miniconda3/lib/python3.8/site-packages/pyews/service/getinboxrules.py", line 43, in __init__
    self.invoke(self._soap_request)
  File "/opt/miniconda3/lib/python3.8/site-packages/pyews/service/serviceendpoint.py", line 104, in invoke
    if parsed_response.find('ResponseCode').string == 'NoError':
AttributeError: 'NoneType' object has no attribute 'string'
```
can you fix it? thank you!

**Comment by nautics889** [comment]
I encounter the same error. The problem is incorrect handling exceptional cases when, for example, you pass wrong credentials as i did... Exchange responses with 401 status code and it fails when pyews try to parse body.
I inspected it with a debugger, I'd set a breakpoint [here](https://github.com/swimlane/pyews/blob/master/pyews/core.py#L53) and look what I saw:
```
(Pdb) parsed_response.find('ResponseCode') is None
True
```
sure `parsed_response.find('ResponseCode').string` would raise an `AttributeError`.
Therefore unprocessed response on it's own is empty:
```
(Pdb) response.status_code
401
(Pdb) response.text
''
```
By the way idk why Exchange didn't send any message, even more: i'm pretty sure i provided correct credentials. It means either something wrong with my EWS or some field in xml request (or SOAP header) is missing / bad format of creds to complete login.

I'm going to fix error handling and create a PR.

**Comment by MSAdministrator** [comment]
@nautics889 @lztby 

I wanted to share that there is a new dev version of py-ews which should resolve this and many other issues:

I have a new development verson of pyews that I would like you to try.

`pip install py-ews-dev==3.1.0`

Once it is installed then create a new Python script file.

Inside that file paste this:

```
from pyews import EWS

ews = EWS(
    'email@company.com,
    'some_password'
)

for item in ews.search_and_delete_message('phish', what_if=True):
    print(item)
```

You should see logs on your console and that is expected. Please let me know how this works for you.
